# General
inferno_logo = "config/logo.txt"
display_logo = true
output_dir = "YOUR_OUTPUT_DIR"
file_types = [".flac", ".mp3", ".m4a"]
valid_cover_art = ["cover.jpg", "front.jpg", "{artist} - {album}.jpg"]
tracklist_filename = "tracklist.txt"
clear_output_dir = false

# imgBB API
imgbb_url = "https://api.imgbb.com/1/upload"
imgbb_api_key = "IMGBB_API_KEY"

# MusicBrainz API
[musicbrainz_user_agent]
name = "YOUR_APP_NAME"
version = "1.0"
email = "YOUR_EMAIL"

# qBittorrent API
[qBittorrent]
qb_url = "YOUR_QB_URL"
username = "QB_USERNAME"
password = "QB_PASSWORD"
category = "MUSIC"
tags = "MUSIC"
# save_path = "/downloads/music/mp3/{artist}"
paused = "false"

# Trackers
[trackers.sometracker]
tracker_announce = "https://TRACKER_DOMAIN/announce/YOUR_ANNOUNCE"
tracker_api_url = "https://TRACKER_DOMAIN/api/torrents/upload"
tracker_api_token = "YOUR_API_TOKEN"
category_id = 3
type_ids = { "flac" = 7, "mp3" = 8 }

[trackers.othertracker]
tracker_announce = "https://othertracker.com/announce/xxx"
tracker_api_url = "https://othertracker.com/api/torrents/upload"
tracker_api_token = "xxx"
category_id = 3
type_ids = { "flac" = 7, "mp3" = 11 }
